export type ProjectStatus = "shipped" | "building" | "planned";

export type ProjectVisualKey = "figma" | "shopify" | "lifeos";

export interface Project {
  index: string;
  title: string;
  status: ProjectStatus;
  statusLabel: string;
  qualifier?: string;
  summary: string;
  stack: readonly string[];
  demonstrates: string;
  visualKey?: ProjectVisualKey;
}

export const FEATURED_PROJECTS: readonly Project[] = [
  {
    index: "01",
    title: "Figma → spec agent",
    status: "shipped",
    statusLabel: "Shipped",
    summary:
      "Claude Code / Cursor agent that turns Figma design handoffs into structured specs in under two minutes. Reads every screen, generates two HTML reports — plain-English for client, technical for developer — every question prioritised, tagged, evidence-backed from the design.",
    stack: ["Claude Code", "Figma MCP", "Structured prompts"],
    demonstrates:
      "Agentic system design, prompt engineering, evidence-backed structured outputs.",
    visualKey: "figma",
  },
  {
    index: "02",
    title: "Shopify product automation",
    status: "shipped",
    statusLabel: "Shipped · Live in production",
    summary:
      "End-to-end publishing pipeline for a Shoothill client. Photos hit Google Drive → automated cropping + background replacement → AI-generated titles and descriptions from the images → published to Shopify with metadata. ~20-node n8n workflow.",
    stack: [
      "n8n",
      "Google Drive",
      "Image processing",
      "Claude (via n8n AI Agent)",
      "Shopify Admin API",
    ],
    demonstrates: "Multi-system orchestration, client-facing AI delivery.",
    visualKey: "shopify",
  },
  {
    index: "03",
    title: "Life-OS",
    status: "shipped",
    statusLabel: "Shipped",
    qualifier: "Active portfolio piece",
    summary:
      "Personal AI operating system on Claude Code, Obsidian, and MCP. Structured vault of identity, goals, projects and patterns. Claude Code reads it on every interaction, writes back as life happens, surfaces contradictions and drift, self-extends with new skills.",
    stack: [
      "Claude Code",
      "Obsidian",
      "MCP (filesystem, Notion, Figma, TaskNotes)",
    ],
    demonstrates:
      "Claude Code custom skill design, MCP integration, multi-tool orchestration, applied AI for personal-business problems.",
    visualKey: "lifeos",
  },
];

export const SECONDARY_PROJECTS: readonly Project[] = [
  {
    index: "04",
    title: "Morning brief agent",
    status: "shipped",
    statusLabel: "Shipped · Paused",
    summary:
      "Daily Telegram brief pulling weather (Open-Meteo), tech news (HN Algolia, RSS), and Notion-stored content. Generated by Claude.",
    stack: [
      "n8n",
      "Open-Meteo",
      "HN Algolia",
      "RSS",
      "Notion",
      "Telegram",
      "Claude",
    ],
    demonstrates:
      "Multi-source data orchestration, LLM integration into a daily-use tool.",
  },
  {
    index: "05",
    title: "Migration agent",
    status: "building",
    statusLabel: "Building",
    qualifier: "Approved internally by Simon",
    summary:
      "Four-phase agentic pipeline for migrating legacy products to a modern stack: Crawl (Browser Use + Playwright) → Code read (static analysis) → LLM synthesis (multimodal screenshots + DOM + source) → Plan generation mapped to the new stack's conventions. First target: Shoothill's Bargate (.NET / ASP.NET Core + React SPA + SQL Server) → DannoMini (TanStack + Cloudflare D1 + Drizzle).",
    stack: [
      "Browser Use",
      "Playwright",
      "Claude API multimodal",
      "Python",
      "Static analysis",
    ],
    demonstrates:
      "Agentic system design, browser automation, multimodal LLM, structured tool use, code analysis.",
  },
  {
    index: "06",
    title: "RAG support assistant",
    status: "planned",
    statusLabel: "Planned · Ship by 30 May 2026",
    summary:
      "Retrieval-augmented Q&A over a real document set with citations. Ingest pipeline (PDF/MD/HTML → chunking → embeddings → vector DB) → retrieval → Claude API → minimal UI. 20-question hand-written eval with retrieval hit-rate and answer-quality scoring.",
    stack: ["Python", "Claude API", "Chroma or Pinecone", "Embeddings"],
    demonstrates: "RAG architecture, vector DBs, retrieval evaluation.",
  },
  {
    index: "07",
    title: "Multi-agent outreach pipeline",
    status: "planned",
    statusLabel: "Planned · Ship by 30 May 2026",
    summary:
      "Three-agent chain (Researcher → Drafter → Critic) with shared state for personalised B2B outreach. Each agent is a Claude API call with structured tool use. Python orchestrator built cold — no LangChain.",
    stack: ["Python", "Claude API", "Structured tool use"],
    demonstrates:
      "Agent orchestration, agent memory, A2A communication, function calling.",
  },
];
